---
- hosts: localhost
  gather_facts: true

  vars:
    example_var: test
    local_user: $USER
    #pkg_manager:  homebrew

  tasks:

    - debug:
        msg: "local_user {{ local_user }}"

  roles:
    #- vim
    - role: vim
      users:
        #  - cartman
        - kenny
    #    #- kyle
    #    #- stan



